class AppUrl {
  static String token =
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZTg1ZDMwM2ViZmViMmE3MjZhN2Q0NTBkMzBmZGYwOGQ5MmE3MWE0NjJmNjBkZjBhMTIyNDk0ZDRlMTUyODQ0OGRiMzhhM2I4ODZmY2RjYzEiLCJpYXQiOjE3MTA0MTM5ODMuODQ2MTAxMDQ1NjA4NTIwNTA3ODEyNSwibmJmIjoxNzEwNDEzOTgzLjg0NjEwMTk5OTI4MjgzNjkxNDA2MjUsImV4cCI6MTc0MTk0OTk4My44NDI4MjQ5MzU5MTMwODU5Mzc1LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.dUGf-HdfkATqdSrIVpuh5FikoXX-hSdtmBmsZUU4IXFa_bTDvAVnk4ZTUsmLPcKLAGmYg55OqDRZ0BnBCNd9IAej6Il8Vr1iv9rz_-mjnsej_din4o7CYFW0cKdsgb24EIeLPsUGUZjxGDGu1s_2bB39JaXlQcr1dwPLb6k7bkos_-5aTnakz0KTGeh2CBhT4T7wsR2oMuQuNmMh4PVB_mxpKhH-E5mo3DFLsyv3wdDbb1O4olVW0OBhxjiJUKIQSPTuCYKxpYAAOVJraknitdZojQwITZlY83_0xqy-5h3k9QyhtPkvPYd28WM2L8o3JEIBwFSSdeEmF1wlBYuYcCoAiphClaFT4o71itxUeUQ2rDH_8xV5EGJTNmmdKpc4FZHIAkZZJ7n-TPVE8HZ56YPxfl-mOiSHJ0BuGVCrV-s8dP8NK_cSqeJ1Q4pwRAPu-at7OReaXkEw006ooZpUymDuUfnt9aJYu8S-DPVqNyOIbjjyUN0QGfbhwYTnziI4Hhj8zYUix-PFvUjEom2qwGdW3LYlgXAyBl04r2nu0RCNdMIqbRNh1wxh0I9nCj-vVE_ZUjI28_spJ4X3XCNCRmdzrk2Qwigoe_VN1xXkSZ3kCOocblcR-XoLjZbcoVzf47Yllzgap8dVnCWHbMMmE9-phNgUxzwG8M-rllC9pjA';
  static var baseURL = 'https://testcrm.thesuperstarshop.com/api/v1/';
  static var loginURL = '${baseURL}login';
  static var leadsURL = '${baseURL}leads';
  static var productsURL = '${baseURL}products';
  static var taxesUrl = '${baseURL}taxes';
  static var editTaxesUrl = '${baseURL}update-tax';
}
